//created on: 30 Dec, 2019
package com.project.dm.loanorigination

import com.project.dm.loanorigination.Applicant;
import com.project.dm.loanorigination.LoanApplication;


rule "Rule-No. Of Previous Defaults > 3"
	when
        loanApplication : LoanApplication( tenure <= (10), 
        		loanAmount <= ( 5 * applicant.employment.income ), 
        		applicant.noOfPreviousDefaults > (3) ) 
        
	then
		loanApplication.getApplicant().setCreditScore("A");
		System.out.println ("Credit score is set a A - No. of payment defaults is above 3.");
end

rule "Rule-LoanAmountBeyondLimit"
	salience 10
	when
        loanApplication : LoanApplication( loanAmount > ( 5 * applicant.employment.income ) ) 
	then
		loanApplication.getApplicant().setCreditScore("A");
		System.out.println ("Credit score is set a A - LoanAmountBeyondLimit.");
end

rule "Rule-No. of Defaults:1-3"
	salience 15
    when
        loanApplication : LoanApplication( tenure <= (10), 
        		loanAmount <= ( 5 * applicant.employment.income ), 
        		applicant.noOfPreviousDefaults >= (1) , applicant.noOfPreviousDefaults <= (3) )        
    then
        loanApplication.getApplicant().setCreditScore("AA");
        System.out.println ("Credit score is set a AA - No. of defaults is less than or equal to 3");

end

rule "Rule- No Issue"
    //include attributes such as "salience" here...
    when
    	loanApplication : LoanApplication( loanAmount <= ( 5 * applicant.employment.income ), applicant.noOfPreviousDefaults == 0 )	
    then
        //actions
		loanApplication.getApplicant().setCreditScore("AAA");
		System.out.println ("Credit score is set a AAA");
end
